services:
  whatsapp_bot:
    build: .
    container_name: whatsapp_bot_ndfinancas
    ports:
      - "8000:8000"  # Porta do bot
    volumes:
      - ./wwebjs_auth:/app/.wwebjs_auth  # Persistência da sessão do WhatsApp
      - ./images:/app/images             # Pastas de imagens
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      # Adicione suas variáveis de ambiente do .env aqui
      - MYSQL_HOST=host_do_banco
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
      - MYSQL_DATABASE=database
    restart: unless-stopped
